### ISSUE TITLE
Problem with setup

### ISSUE THREAD

**Issue by chrsBlank** [seatsurfing/backend#214]
Hi,

Im trying to setup the docker seatsurfing but i can not succeed.
Im doing it on my docker desktop on my windows 11 computer with the following compose file

```
version: '3.7'

services:
  server:
    image: seatsurfing/backend
    restart: always
    networks:
      sql:
      http:
    ports:
      - 8080:8080
    environment:
      POSTGRES_URL: 'postgres://seatsurfing:DB_PASSWORD@db/seatsurfing?sslmode=disable'
      JWT_SIGNING_KEY: 'some_random_string'
      BOOKING_UI_BACKEND: 'localhost:3001'
      ADMIN_UI_BACKEND: 'localhost:3000'
      PUBLIC_URL: 'http://localhost'
      FRONTEND_URL: 'http://localhost'
  booking-ui:
    image: seatsurfing/booking-ui
    restart: always
    networks:
      http:
    ports:
      - 3001:3001
    environment:
      FRONTEND_URL: 'http://localhost:3001'
  admin-ui:
    image: seatsurfing/admin-ui
    restart: always
    networks:
      sql:
      http:
    ports:
      - 3000:3000
    environment:
      FRONTEND_URL: 'http://localhost:3000'
  db:
    image: postgres:12
    restart: always
    networks:
      sql:
      http:
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: DB_PASSWORD
      POSTGRES_USER: seatsurfing
      POSTGRES_DB: seatsurfing

volumes:
  db:

networks:
  sql:
  http:
```

before you ask, yes thats the default stuff, im just trying to see if it works : (

i have inputed http over https because it says SSL error, and hard coded the ports because it could not find them.

now i get the following error on login: 
![image](https://github.com/seatsurfing/backend/assets/36511746/b3a06aa6-9019-4f3b-9c32-9d89dbd28d28)

all of the containers are up and running without errors btw, i cant see any logs and the connection to the database is present

Thank you in advance
