### ISSUE TITLE
404 on first admin email entry

### ISSUE THREAD

**Issue by TadeSF** [seatsurfing/backend#244]
When I open https://myurl.domain/admin for the first time, I can see the dashboard. But once I enter any email address and send it, i get an instant 404.

Same on localhost:8080 (or 8812 in my case, which is the port I've mapped 8080 to).

![CleanShot 2024-06-08 at 12 03 09@2x](https://github.com/seatsurfing/backend/assets/42637916/df38c9e7-ab19-42db-837b-e85384af5734)

This is my docker-compose file:

```
version: "3.7"

services:
  server:
    image: ghcr.io/seatsurfing/backend
    restart: unless-stopped
    networks:
      sql:
      traefik_default:
      http:
    ports:
      - 8812:8080
    environment:
      POSTGRES_URL: "postgres://seatsurfing:${DB_PW}@db/seatsurfing?sslmode=disable"
      JWT_SIGNING_KEY: ${JWT_SIGNING_KEY}
      INIT_ORG_NAME: "DMUN"
      INIT_ORG_DOMAIN: "tolga.casa"
      INIT_ORG_USER: "admin"
      INIT_ORG_PASS: "admin"
      ORG_SIGNUP_MAX_USERS: 100
      PUBLIC_URL: "https://myurl.domain"
      FRONTEND_URL: "https://myurl.domain"
      BOOKING_UI_BACKEND: 'booking-ui:3001'
      ADMIN_UI_BACKEND: 'admin-ui:3000'
      PRINT_CONFIG: 1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.raumbuchung-api.rule=Host(`myurl.domain`)"
      - "traefik.http.routers.raumbuchung-api.entrypoints=websecure"
      - "traefik.http.routers.raumbuchung-api.tls.certresolver=myresolver"

  booking-ui:
    image: ghcr.io/seatsurfing/booking-ui
    restart: unless-stopped
    environment:
      FRONTEND_URL: "https://myurl.domain"
    networks:
      http:

  admin-ui:
    image: ghcr.io/seatsurfing/admin-ui
    restart: unless-stopped
    environment:
      FRONTEND_URL: "https://myurl.domain"
    networks:
      http:

  db:
    image: postgres:16
    restart: unless-stopped
    networks:
      sql:
    volumes:
      - ${PERSISTED}/seatsurfers:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PW}
      POSTGRES_USER: seatsurfing
      POSTGRES_DB: seatsurfing

networks:
  sql:
  traefik_default:
    external: true
  http:

```
