### ISSUE TITLE
After  v1.35.3 login fails with: http: server gave HTTP response to HTTPS client

### ISSUE THREAD

**Issue by alessioc42** [seatsurfing/backend#981]
I have this docker-compose running behind a reverse proxy configured as follows:

Compose:
```yaml
version: '3.7'

services:
  server:
    image: ghcr.io/seatsurfing/backend
    restart: always
    networks:
      sql:
      http:
    ports:
      - 8080:8080
    environment:
      POSTGRES_URL: 'postgres://seatsurfing:DB_PASSWORD@db/seatsurfing?sslmode=disable'
      BOOKING_UI_BACKEND: 'booking-ui:3001'
      ADMIN_UI_BACKEND: 'admin-ui:3000'
      CRYPT_KEY: '________________________________________'
      INIT_ORG_NAME: 'My-Org-Name'
      INIT_ORG_LANGUAGE: 'de'
  booking-ui:
    image: ghcr.io/seatsurfing/booking-ui
    restart: always
    networks:
      http:
  admin-ui:
    image: ghcr.io/seatsurfing/admin-ui
    restart: always
    networks:
      http:
  db:
    image: postgres:16
    restart: always
    networks:
      sql:
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: DB_PASSWORD
      POSTGRES_USER: seatsurfing
      POSTGRES_DB: seatsurfing

volumes:
  db:

networks:
  sql:
  http:
```

and here is the nginx conf running on the host:
```conf
server {
    listen 80;
    server_name seatsurfing.myDomain.de;
    return 301 https://seatsurfing.myDomain.de;
}

server {
    listen 443 ssl;
    server_name seatsurfing.myDomain.de;

    ssl_certificate /etc/letsencrypt/live/seatsurfing.myDomain.de/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/seatsurfing.myDomain.de/privkey.pem;

    location / {
        proxy_pass http://localhost:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

```

I also have SSO setup and it was working.

Loggin in with a normal user account is no problem.

Loggin in with a normal admin account is no problem either, until I want to go to the admin settings: The Browser displays a Page: 
```
Get "https://seatsurfing.myDomain.de:3000/admin/en/dashboard": http: server gave HTTP response to HTTPS client
```

Similarly, when authenticating via SSO, I recieve:
```
Get "https://seatsurfing.myDomain.de:3001/ui/en/login/success/f7802deb-863c-4b76-9ca0-ae674397bb39": http: server gave HTTP response to HTTPS client
```

The Problem did not exist until I updated to v1.35.3
I figured, maybe it has something to do with #951 ?
But I could not find any logical errors or something around these parts.
